language: python
python:
- '3.4'
- '3.5'
- '3.6'
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  # - pip install cython
  # - pip install numpy pandas scipy
  # - git clone https://github.com/facebookresearch/fastText.git
  # - cd fastText
  # - pip install .
  # - cd ..
  # - pip install scikit-learn
  - pip install codecov
install:
  - pip install ".[test,fasttext]" --process-dependency-links
script: pytest
after_success:
  - codecov
