language: python
python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - os: osx
      language: minimal
      install: pip3 install -e .[tests]
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
# env:
#   - TO_RUN=TESTS
#   - TO_RUN=BUILD
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  # - pip install cython
  # - pip install numpy pandas scipy
  # - git clone https://github.com/facebookresearch/fastText.git
  # - cd fastText
  # - pip install .
  # - cd ..
  # - pip install scikit-learn
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest
  # - pip install git+https://github.com/facebookresearch/fastText.git@ca8c5face7d5f3a64fff0e4dfaf58d60a691cb7c
  # - pip3 install git+git://github.com/facebookresearch/fastText.git@0a5759475265705b485fa9fae4d1186d248049aa
  - pip3 install codecov
install:
  pip3 install ".[test]" 
script:
  - pip3 list
  - python3 -m pytest
  - python3 -m codecov
# after_success:
  # - codecov
