language: python
python:
  - '3.5'
  - '3.6'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# env:
#   - TO_RUN=TESTS
#   - TO_RUN=BUILD
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  # - pip install cython
  # - pip install numpy pandas scipy
  # - git clone https://github.com/facebookresearch/fastText.git
  # - cd fastText
  # - pip install .
  # - cd ..
  # - pip install scikit-learn
  - pip install -U pip
  - pip install -U pytest
  # - pip install git+https://github.com/facebookresearch/fastText.git@ca8c5face7d5f3a64fff0e4dfaf58d60a691cb7c
  - pip install git+git://github.com/facebookresearch/fastText.git@0a5759475265705b485fa9fae4d1186d248049aa
  - pip install codecov
install:
       pip install ".[test]" 
script:
  - pytest
  - codecov
# after_success:
  # - codecov
